# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - Rscript -e 'install.packages(c("waldo", "covr", "ggplot2", "dplyr"))'

after_success:
    - Rscript -e 'covr::codecov()'
