# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

apt_packages:
  - r-cran-rjava

before_install:
  - sudo $(which R) CMD javareconf

after_success:
  - Rscript -e 'covr::codecov()'
